CREATE TABLE product_data (
  id BIGSERIAL PRIMARY KEY,
  product_id TEXT NOT NULL UNIQUE,
  product_name TEXT NOT NULL,
  cost DOUBLE PRECISION NOT NULL,
  lead_time_months DOUBLE PRECISION NOT NULL,
  ordering_cost DOUBLE PRECISION NOT NULL,
  holding_cost DOUBLE PRECISION NOT NULL,
  eoq DOUBLE PRECISION NOT NULL,
  rop DOUBLE PRECISION NOT NULL,
  ss DOUBLE PRECISION NOT NULL,
  dl DOUBLE PRECISION NOT NULL,
  forecast DOUBLE PRECISION NOT NULL,
  dmd_stdev DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_product_data_product_id ON product_data(product_id);